env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module

plugins: ["react", "react-hooks", "@typescript-eslint"]

extends:
  [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:import/react",
    "plugin:@typescript-eslint/recommended",
  ]

settings:
  react:
    version: "16"
  import/resolver:
    node:
      extensions: [".js", ".jsx"]

rules:
  {
    "no-console": "warn",
    "react/react-in-jsx-scope": "off",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps":
      ["warn", { "additionalHooks": "(useMyCustomHook|useMyOtherCustomHook)" }],
    "no-loss-of-precision": "off",
    "@typescript-eslint/no-loss-of-precision": ["error"],
    "@typescript-eslint/ban-ts-comment": "warn",
    "@typescript-eslint/no-unused-vars": "warn",
    "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
    "indent": ["error", 2],
    "one-var-declaration-per-line": ["error", "always"],
    "no-multiple-empty-lines":
      ["error", { "max": 2, "maxEOF": 0, "maxBOF": 0 }],
    "padding-line-between-statements":
      [
        "error",
        { blankLine: "always", prev: "directive", next: "*" },
        { blankLine: "any", prev: "directive", next: "directive" },
        { blankLine: "always", prev: "*", next: "export" },
        { blankLine: "any", prev: "export", next: "export" },
        { blankLine: "always", prev: "import", next: "*" },
        { blankLine: "any", prev: "import", next: "import" },
      ],
    "no-trailing-spaces": "error",
    "key-spacing":
      ["error", { "beforeColon": false, "afterColon": true, "mode": "strict" }],
    "function-call-argument-newline": ["error", "consistent"],
    "comma-dangle":
      [
        "error",
        {
          "arrays": "always-multiline",
          "objects": "always-multiline",
          "imports": "always-multiline",
          "exports": "always",
          "functions": "only-multiline",
        },
      ],
    "object-curly-newline": [
        "error",
        {
          # "ObjectExpression": { "multiline": true, "minProperties": 1 },
          # "ObjectPattern": "always", #{ "multiline": true },
          "ImportDeclaration": { "multiline": true, "minProperties": 5 },
          "ExportDeclaration": "always",
        },
      ],
    "object-property-newline":
      ["error", { "allowAllPropertiesOnSameLine": true }],
    "jsx-quotes": ["error", "prefer-double"],
    "quotes": ["error", "double", { "allowTemplateLiterals": true }],
    "semi-spacing": ["error", { "before": false, "after": true }],
    "semi-style": ["error", "last"],
    "semi": "off",
    "@typescript-eslint/semi": ["error"],
    "spaced-comment": "warn",
    "no-multi-spaces": "error",
    "no-whitespace-before-property": "error",
  }
